### ISSUE TITLE
Verification should determine the isomorphism classes of the KS candidates

### ISSUE THREAD

**Issue by curtisbright** [curtisbright/PhysicsCheck#1]
The verification script should remove any KS candidates that are isomorphic to each other and verify that all the remaining KS candidates are mutually nonisomorphic.  The paper currently says this was checked with NetworkX and SageMath but it is not in the pipeline.

**Comment by BrianLi009** [comment]
script pushed, will connect the script to the main pipeline once it's cleaned up.
