### ISSUE TITLE
Isomorphism checking error

### ISSUE THREAD

**Issue by curtisbright** [curtisbright/PhysicsCheck#20]
checking solutions are unique up to isomorphism...
Traceback (most recent call last):
  File "/home/cbright/PhysicsCheck_cbright/non_iso_verify.py", line 46, in <module>
    verify(sys.argv[1], sys.argv[2])
  File "/home/cbright/PhysicsCheck_cbright/non_iso_verify.py", line 31, in verify
    hash = get_hash(G)
  File "/home/cbright/PhysicsCheck_cbright/non_iso_verify.py", line 20, in get_hash
    return nx.weisfeiler_lehman_graph_hash(G)
AttributeError: module 'networkx' has no attribute 'weisfeiler_lehman_graph_hash'

**Comment by BrianLi009** [comment]
I tried to run it on my end and did not get this error. It could be a networkx version issue. What is the version of NetworkX you are using?

**Comment by curtisbright** [comment]
$ pip3 list | grep networkx
networkx                 2.4

**Comment by BrianLi009** [comment]
pip3 list | grep networkx
networkx                2.6.3

I'll specify the version in dependency-setup.sh, will look into exactly which versions have this.

**Comment by BrianLi009** [comment]
It's introduced in version 2.5, so any version newer than that should work:

https://networkx.org/documentation/stable/release/release_2.5.html
