### ISSUE TITLE
Handle cube file stored in a sub-directory for `solve-single-cube.sh`

### ISSUE THREAD

**Issue by piyush-J** [curtisbright/PhysicsCheck#21]
We get an error if we have the cube file stored in the sub-directory, e.g., in the snippet given below, `4.cubes` is stored in `19-files/19-cubes`:

```
./solve-single-cube.sh 19 constraints_19_c_100000_2_2_0_final.simp 19-files/19-cubes/4.cubes
```

The current hack is to move `4.cubes` into the main directory and use: 

```
./solve-single-cube.sh 19 constraints_19_c_100000_2_2_0_final.simp 4.cubes
```

**Comment by BrianLi009** [comment]
Issue is resolved. I've tested the new script and the following command should work now:
`./solve-single-cube.sh 19 constraints_19_c_100000_2_2_0_final.simp 19-files/19-cubes/4.cubes 1`
